# Generated by Django 3.1.4 on 2020-12-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='public_reply',
            new_name='public',
        ),
    ]
