# Generated by Django 3.1.4 on 2020-12-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20201226_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
